
package net.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CrearAlumnoPortType", targetNamespace = "urn:CrearAlumno")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CrearAlumnoPortType {


    /**
     * Service definition of function ns__getInfo
     * 
     * @param insert
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "recepcion", targetNamespace = "")
    @RequestWrapper(localName = "getInfo", targetNamespace = "urn:CrearAlumno", className = "crearalumno.GetInfo")
    @ResponseWrapper(localName = "getInfoResponse", targetNamespace = "urn:CrearAlumno", className = "crearalumno.GetInfoResponse")
    public String getInfo(
        @WebParam(name = "insert", targetNamespace = "")
        Input insert);

}
