
package crearalumno;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * gSOAP 2.8.36 generated service definition
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CrearAlumno", targetNamespace = "urn:CrearAlumno", wsdlLocation = "http://localhost/CrearAlumno.wsdl")
public class CrearAlumno
    extends Service
{

    private final static URL CREARALUMNO_WSDL_LOCATION;
    private final static WebServiceException CREARALUMNO_EXCEPTION;
    private final static QName CREARALUMNO_QNAME = new QName("urn:CrearAlumno", "CrearAlumno");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/CrearAlumno.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREARALUMNO_WSDL_LOCATION = url;
        CREARALUMNO_EXCEPTION = e;
    }

    public CrearAlumno() {
        super(__getWsdlLocation(), CREARALUMNO_QNAME);
    }

    public CrearAlumno(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREARALUMNO_QNAME, features);
    }

    public CrearAlumno(URL wsdlLocation) {
        super(wsdlLocation, CREARALUMNO_QNAME);
    }

    public CrearAlumno(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREARALUMNO_QNAME, features);
    }

    public CrearAlumno(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrearAlumno(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CrearAlumnoPortType
     */
    @WebEndpoint(name = "CrearAlumno")
    public CrearAlumnoPortType getCrearAlumno() {
        return super.getPort(new QName("urn:CrearAlumno", "CrearAlumno"), CrearAlumnoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrearAlumnoPortType
     */
    @WebEndpoint(name = "CrearAlumno")
    public CrearAlumnoPortType getCrearAlumno(WebServiceFeature... features) {
        return super.getPort(new QName("urn:CrearAlumno", "CrearAlumno"), CrearAlumnoPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREARALUMNO_EXCEPTION!= null) {
            throw CREARALUMNO_EXCEPTION;
        }
        return CREARALUMNO_WSDL_LOCATION;
    }

}
